# Generated by Django 3.2.9 on 2022-09-14 07:59

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(
                    auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(
                    auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('picture', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('price', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=6)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('condition', models.CharField(
                    blank=True, default='', max_length=64)),
                ('scrape', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
