# Generated by Django 3.2.9 on 2022-09-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-modified'], 'verbose_name_plural': 'Card Links'},
        ),
        migrations.RenameField(
            model_name='card',
            old_name='scrape',
            new_name='is_scrape',
        ),
        migrations.AddField(
            model_name='card',
            name='card_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(blank=True, choices=[('list', 'List'), ('sealed', 'Sealed'), ('single_card', 'Single Card')], default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['title', 'category'], name='card_links_title_7568c2_idx'),
        ),
        migrations.AlterModelTable(
            name='card',
            table='card_links',
        ),
    ]
