# Generated by Django 3.2.9 on 2022-09-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_card_link_subscene'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='link_subscene',
            new_name='link_tcgplayer',
        ),
    ]
