# Generated by Django 3.2.9 on 2022-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_link_subscene_card_link_tcgplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='presale_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='presale_note_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='seller',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='link_tcgplayer',
            field=models.URLField(),
        ),
    ]
