# Generated by Django 3.2.9 on 2022-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220916_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='link_tcgplayer',
            field=models.URLField(default='', null=True),
        ),
    ]
