# Generated by Django 3.2.9 on 2022-09-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_card_link_tcgplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
