# Generated by Django 3.2.9 on 2022-09-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220916_0932'),
        ('app', '0006_auto_20220917_0813'),
    ]

    operations = [
    ]
