# Generated by Django 3.2.9 on 2022-09-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_0002_auto_20220916_0932_0006_auto_20220917_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='link_tcgplayer',
        ),
        migrations.AddField(
            model_name='card',
            name='run_immediately',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='card',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
