# Generated by Django 3.2.9 on 2022-09-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220926_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_upload',
            field=models.BooleanField(default=False),
        ),
    ]
