# Generated by Django 3.2.9 on 2022-09-30 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0009_card_is_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('shopify_api_key', models.CharField(blank=True, default='', max_length=128)),
                ('shopify_secret_key', models.CharField(blank=True, default='', max_length=128)),
                ('shopify_url', models.CharField(blank=True, default='', max_length=128)),
                ('shopify_access_token', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
