# Generated by Django 3.2.9 on 2022-09-30 04:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_alter_preferences_id'),
        ('app', '0010_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPreferences',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.preferences')),
                ('shopify_api_key', models.CharField(blank=True, default='', max_length=128)),
                ('shopify_secret_key', models.CharField(blank=True, default='', max_length=128)),
                ('shopify_url', models.CharField(blank=True, default='', max_length=128)),
                ('shopify_access_token', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Preferences',
            },
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
