# Generated by Django 3.2.9 on 2022-10-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220930_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypreferences',
            name='shopify_access_token',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='mypreferences',
            name='shopify_api_key',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='mypreferences',
            name='shopify_secret_key',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='mypreferences',
            name='shopify_url',
            field=models.URLField(max_length=512),
        ),
    ]
