# Generated by Django 3.2.9 on 2022-10-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20221003_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='scrape_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='shopify_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='tcgplayer_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
