# Generated by Django 3.2.9 on 2022-10-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20221007_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypreferences',
            name='location_id',
            field=models.CharField(default='', max_length=128),
        ),
    ]
