# Generated by Django 3.2.9 on 2022-10-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_card_scrape_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypreferences',
            name='import_example_id',
            field=models.URLField(default='https://drive.google.com/file/d/1zHFF_UCAoGRDsXUJjSn2FgQXr9zkoCsw/view?usp=sharing', help_text='READ ONLY FIELD'),
        ),
        migrations.AlterField(
            model_name='mypreferences',
            name='location_id',
            field=models.CharField(default='', help_text='This is ...', max_length=128),
        ),
    ]
