# Generated by Django 3.2.9 on 2022-10-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20221013_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypreferences',
            name='import_example_id',
        ),
        migrations.AddField(
            model_name='mypreferences',
            name='import_example_file',
            field=models.URLField(default='https://drive.google.com/file/d/1zHFF_UCAoGRDsXUJjSn2FgQXr9zkoCsw/view?usp=sharing', help_text='Download importing template file'),
        ),
        migrations.AlterField(
            model_name='mypreferences',
            name='location_id',
            field=models.CharField(default='', help_text='Shopify inventory location id', max_length=128),
        ),
    ]
