# Generated by Django 3.2.9 on 2022-10-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20221013_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
